 
# Prebuilts lib
PRODUCT_COPY_FILES += \
    device/zte/hayes/original_rom/system/lib/drmclientlib.so:system/lib/drmclientlib.so \
    device/zte/hayes/original_rom/system/lib/libacdbloader.so:system/lib/libacdbloader.so \
    device/zte/hayes/original_rom/system/lib/libairtunes.so:system/lib/libairtunes.so \
    device/zte/hayes/original_rom/system/lib/libakmd.so:system/lib/libakmd.so \
    device/zte/hayes/original_rom/system/lib/libalarmservice_jni.so:system/lib/libalarmservice_jni.so \
    device/zte/hayes/original_rom/system/lib/liballjoyn.so:system/lib/liballjoyn.so \
    device/zte/hayes/original_rom/system/lib/libalsa-intf.so:system/lib/libalsa-intf.so \
    device/zte/hayes/original_rom/system/lib/libalsautils.so:system/lib/libalsautils.so \
    device/zte/hayes/original_rom/system/lib/libami_sensor_mw.so:system/lib/libami_sensor_mw.so \
    device/zte/hayes/original_rom/system/lib/libami.so:system/lib/libami.so \
    device/zte/hayes/original_rom/system/lib/libaudcal.so:system/lib/libaudcal.so \
    device/zte/hayes/original_rom/system/lib/libaudioalsa.so:system/lib/libaudioalsa.so \
    device/zte/hayes/original_rom/system/lib/libaudioparameter.so:system/lib/libaudioparameter.so \
    device/zte/hayes/original_rom/system/lib/libbluedroid.so:system/lib/libbluedroid.so \
    device/zte/hayes/original_rom/system/lib/libbluetoothd.so:system/lib/libbluetoothd.so \
    device/zte/hayes/original_rom/system/lib/libbluetooth.so:system/lib/libbluetooth.so \
    device/zte/hayes/original_rom/system/lib/libbson.so:system/lib/libbson.so \
    device/zte/hayes/original_rom/system/lib/libbtio.so:system/lib/libbtio.so \
    device/zte/hayes/original_rom/system/lib/libC2D2.so:system/lib/libC2D2.so \
    device/zte/hayes/original_rom/system/lib/libcneapiclient.so:system/lib/libcneapiclient.so \
    device/zte/hayes/original_rom/system/lib/libcneqmiutils.so:system/lib/libcneqmiutils.so \
    device/zte/hayes/original_rom/system/lib/libcneutils.so:system/lib/libcneutils.so \
    device/zte/hayes/original_rom/system/lib/libCommandSvc.so:system/lib/libCommandSvc.so \
    device/zte/hayes/original_rom/system/lib/libconfigdb.so:system/lib/libconfigdb.so  \
    device/zte/hayes/original_rom/system/lib/libcurl.so:system/lib/libcurl.so  \
    device/zte/hayes/original_rom/system/lib/libcurvecore_oem.so:system/lib/libcurvecore_oem.so  \
    device/zte/hayes/original_rom/system/lib/libcurve_oem.so:system/lib/libcurve_oem.so  \
    device/zte/hayes/original_rom/system/lib/libDiagService.so:system/lib/libDiagService.so  \
    device/zte/hayes/original_rom/system/lib/libdiag.so:system/lib/libdiag.so  \
    device/zte/hayes/original_rom/system/lib/libDivxDrm.so:system/lib/libDivxDrm.so \
    device/zte/hayes/original_rom/system/lib/libdnshostprio.so:system/lib/libdnshostprio.so \
    device/zte/hayes/original_rom/system/lib/libdrmdiag.so:system/lib/libdrmdiag.so \
    device/zte/hayes/original_rom/system/lib/libdrmfs.so:system/lib/libdrmfs.so \
    device/zte/hayes/original_rom/system/lib/libdrmtime.so:system/lib/libdrmtime.so \
    device/zte/hayes/original_rom/system/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
    device/zte/hayes/original_rom/system/lib/libdsprofile.so:system/lib/libdsprofile.so \
    device/zte/hayes/original_rom/system/lib/libdss.so:system/lib/libdss.so \
    device/zte/hayes/original_rom/system/lib/libdsucsd.so:system/lib/libdsucsd.so \
    device/zte/hayes/original_rom/system/lib/libdsutils.so:system/lib/libdsutils.so \
    device/zte/hayes/original_rom/system/lib/libemode_jni.so:system/lib/libemode_jni.so \
    device/zte/hayes/original_rom/system/lib/libfacelock_jni.so:system/lib/libfacelock_jni.so \
    device/zte/hayes/original_rom/system/lib/libfastcvopt.so:system/lib/libfastcvopt.so \
    device/zte/hayes/original_rom/system/lib/libFileMux.so:system/lib/libFileMux.so \
    device/zte/hayes/original_rom/system/lib/libfilterpack_facedetect.so:system/lib/libfilterpack_facedetect.so \
    device/zte/hayes/original_rom/system/lib/libflint_engine_jni_api.so:system/lib/libflint_engine_jni_api.so \
    device/zte/hayes/original_rom/system/lib/libfrsdk.so:system/lib/libfrsdk.so \
    device/zte/hayes/original_rom/system/lib/libgcomm_jni.so:system/lib/libgcomm_jni.so \
    device/zte/hayes/original_rom/system/lib/libgemini.so:system/lib/libgemini.so \
    device/zte/hayes/original_rom/system/lib/libgeofence.so:system/lib/libgeofence.so \
    device/zte/hayes/original_rom/system/lib/libGLESv2_dbg.so:system/lib/libGLESv2_dbg.so \
    device/zte/hayes/original_rom/system/lib/libglib.so:system/lib/libglib.so \
    device/zte/hayes/original_rom/system/lib/libgps.so:system/lib/libgps.so \
    device/zte/hayes/original_rom/system/lib/libgps.utils.so:system/lib/libgps.utils.so \
    device/zte/hayes/original_rom/system/lib/libgsl.so:system/lib/libgsl.so \
    device/zte/hayes/original_rom/system/lib/libhwui.so:system/lib/libhwui.so \
    device/zte/hayes/original_rom/system/lib/libI420colorconvert.so:system/lib/libI420colorconvert.so \
    device/zte/hayes/original_rom/system/lib/libidl.so:system/lib/libidl.so \
    device/zte/hayes/original_rom/system/lib/libimage-jpeg-dec-omx-comp.so:system/lib/libimage-jpeg-dec-omx-comp.so \
    device/zte/hayes/original_rom/system/lib/libimage-jpeg-enc-omx-comp.so:system/lib/libimage-jpeg-enc-omx-comp.so \
    device/zte/hayes/original_rom/system/lib/libimage-omx-common.so:system/lib/libimage-omx-common.so \
    device/zte/hayes/original_rom/system/lib/libllvm-a3xx.so:system/lib/libllvm-a3xx.so \
    device/zte/hayes/original_rom/system/lib/libloc_adapter.so:system/lib/libloc_adapter.so \
    device/zte/hayes/original_rom/system/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
    device/zte/hayes/original_rom/system/lib/libloc_eng.so:system/lib/libloc_eng.so \
    device/zte/hayes/original_rom/system/lib/libloc_ext.so:system/lib/libloc_ext.so \
    device/zte/hayes/original_rom/system/lib/libminui_ftm.so:system/lib/libminui_ftm.so \
    device/zte/hayes/original_rom/system/lib/libminzip_ftm.so:system/lib/libminzip_ftm.so \
    device/zte/hayes/original_rom/system/lib/libmm-abl-oem.so:system/lib/libmm-abl-oem.so \
    device/zte/hayes/original_rom/system/lib/libmm-abl.so:system/lib/libmm-abl.so \
    device/zte/hayes/original_rom/system/lib/libmm-audio-resampler.so:system/lib/libmm-audio-resampler.so \
    device/zte/hayes/original_rom/system/lib/libmmcamera_faceproc.so:system/lib/libmmcamera_faceproc.so \
    device/zte/hayes/original_rom/system/lib/libmmcamera_frameproc.so:system/lib/libmmcamera_frameproc.so \
    device/zte/hayes/original_rom/system/lib/libmmcamera_statsproc30.so:system/lib/libmmcamera_statsproc30.so \
    device/zte/hayes/original_rom/system/lib/libmm-color-convertor.so:system/lib/libmm-color-convertor.so \
    device/zte/hayes/original_rom/system/lib/libmmhttpstack.so:system/lib/libmmhttpstack.so \
    device/zte/hayes/original_rom/system/lib/libmmiipstreammmihttp.so:system/lib/libmmiipstreammmihttp.so \
    device/zte/hayes/original_rom/system/lib/libmmipl.so:system/lib/libmmipl.so \
    device/zte/hayes/original_rom/system/lib/libmmipstreamaal.so:system/lib/libmmipstreamaal.so \
    device/zte/hayes/original_rom/system/lib/libmmipstreamnetwork.so:system/lib/libmmipstreamnetwork.so \
    device/zte/hayes/original_rom/system/lib/libmmipstreamsourcehttp.so:system/lib/libmmipstreamsourcehttp.so \
    device/zte/hayes/original_rom/system/lib/libmmipstreamutils.so:system/lib/libmmipstreamutils.so \
    device/zte/hayes/original_rom/system/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    device/zte/hayes/original_rom/system/lib/libmmjps.so:system/lib/libmmjps.so \
    device/zte/hayes/original_rom/system/lib/libmmmpod.so:system/lib/libmmmpod.so \
    device/zte/hayes/original_rom/system/lib/libmmmpo.so:system/lib/libmmmpo.so \
    device/zte/hayes/original_rom/system/lib/libmmosal.so:system/lib/libmmosal.so \
    device/zte/hayes/original_rom/system/lib/libmmparser.so:system/lib/libmmparser.so \
    device/zte/hayes/original_rom/system/lib/libmmQSM.so:system/lib/libmmQSM.so \
    device/zte/hayes/original_rom/system/lib/libmmrtpencoder.so:system/lib/libmmrtpencoder.so \
    device/zte/hayes/original_rom/system/lib/libmmstereo.so:system/lib/libmmstereo.so \
    device/zte/hayes/original_rom/system/lib/libmmstillomx.so:system/lib/libmmstillomx.so \
    device/zte/hayes/original_rom/system/lib/libmmwfdinterface.so:system/lib/libmmwfdinterface.so \
    device/zte/hayes/original_rom/system/lib/libmmwfdsinkinterface.so:system/lib/libmmwfdsinkinterface.so \
    device/zte/hayes/original_rom/system/lib/libmmwfdsrcinterface.so:system/lib/libmmwfdsrcinterface.so \
    device/zte/hayes/original_rom/system/lib/libMNDProxy.so:system/lib/libMNDProxy.so \
    device/zte/hayes/original_rom/system/lib/libnanosmevent.so:system/lib/libnanosmevent.so \
    device/zte/hayes/original_rom/system/lib/libnanotitan.so:system/lib/libnanotitan.so \
    device/zte/hayes/original_rom/system/lib/libnetmgr.so:system/lib/libnetmgr.so \
    device/zte/hayes/original_rom/system/lib/libnetmonitor.so:system/lib/libnetmonitor.so \
    device/zte/hayes/original_rom/system/lib/libnfc_jni.so:system/lib/libnfc_jni.so \
    device/zte/hayes/original_rom/system/lib/libnfc.so:system/lib/libnfc.so \
    device/zte/hayes/original_rom/system/lib/libNimsWrap.so:system/lib/libNimsWrap.so \
    device/zte/hayes/original_rom/system/lib/libnmc-jni.so:system/lib/libnmc-jni.so \
    device/zte/hayes/original_rom/system/lib/libnmsp_speex.so:system/lib/libnmsp_speex.so \
    device/zte/hayes/original_rom/system/lib/liboemcamera.so:system/lib/liboemcamera.so \
    device/zte/hayes/original_rom/system/lib/libOmxAacDec.so:system/lib/libOmxAacDec.so \
    device/zte/hayes/original_rom/system/lib/libOmxAacEnc.so:system/lib/libOmxAacEnc.so \
    device/zte/hayes/original_rom/system/lib/libOmxAmrEnc.so:system/lib/libOmxAmrEnc.so \
    device/zte/hayes/original_rom/system/lib/libOmxEvrcDec.so:system/lib/libOmxEvrcDec.so \
    device/zte/hayes/original_rom/system/lib/libOmxEvrcEnc.so:system/lib/libOmxEvrcEnc.so \
    device/zte/hayes/original_rom/system/lib/libOmxMux.so:system/lib/libOmxMux.so \
    device/zte/hayes/original_rom/system/lib/libOmxQcelp13Dec.so:system/lib/libOmxQcelp13Dec.so \
    device/zte/hayes/original_rom/system/lib/libOmxQcelp13Enc.so:system/lib/libOmxQcelp13Enc.so \
    device/zte/hayes/original_rom/system/lib/libOmxWmaDec.so:system/lib/libOmxWmaDec.so \
    device/zte/hayes/original_rom/system/lib/libOpenCL.so:system/lib/libOpenCL.so \
    device/zte/hayes/original_rom/system/lib/libOpenVG.so:system/lib/libOpenVG.so \
    device/zte/hayes/original_rom/system/lib/libpicowrapper.so:system/lib/libpicowrapper.so \
    device/zte/hayes/original_rom/system/lib/libpng.so:system/lib/libpng.so \
    device/zte/hayes/original_rom/system/lib/libprofiler_msmadc.so:system/lib/libprofiler_msmadc.so \
    device/zte/hayes/original_rom/system/lib/libpvandroidmio_apple_render_froyo.so:system/lib/libpvandroidmio_apple_render_froyo.so \
    device/zte/hayes/original_rom/system/lib/libpvandroidmio_apple_render_gb.so:system/lib/libpvandroidmio_apple_render_gb.so \
    device/zte/hayes/original_rom/system/lib/libpvandroidmio_apple_render_hc.so:system/lib/libpvandroidmio_apple_render_hc.so \
    device/zte/hayes/original_rom/system/lib/libpvandroidmio_apple_render_ics.so:system/lib/libpvandroidmio_apple_render_ics.so \
    device/zte/hayes/original_rom/system/lib/libpvandroidmio_apple_render_pre_froyo.so:system/lib/libpvandroidmio_apple_render_pre_froyo.so \
    device/zte/hayes/original_rom/system/lib/libpvplayerservice.so:system/lib/libpvplayerservice.so \
    device/zte/hayes/original_rom/system/lib/libqcci_adc.so:system/lib/libqcci_adc.so \
    device/zte/hayes/original_rom/system/lib/libQcomUI.so:system/lib/libQcomUI.so \
    device/zte/hayes/original_rom/system/lib/libqc-opt.so:system/lib/libqc-opt.so \
    device/zte/hayes/original_rom/system/lib/libqdi.so:system/lib/libqdi.so \
    device/zte/hayes/original_rom/system/lib/libqdp.so:system/lib/libqdp.so \
    device/zte/hayes/original_rom/system/lib/libqmi_cci.so:system/lib/libqmi_cci.so \
    device/zte/hayes/original_rom/system/lib/libqmi_common_so.so:system/lib/libqmi_common_so.so \
    device/zte/hayes/original_rom/system/lib/libqmi_csi.so:system/lib/libqmi_csi.so \
    device/zte/hayes/original_rom/system/lib/libqmi_encdec.so:system/lib/libqmi_encdec.so \
    device/zte/hayes/original_rom/system/lib/libqmiservices.so:system/lib/libqmiservices.so \
    device/zte/hayes/original_rom/system/lib/libqmi.so:system/lib/libqmi.so \
    device/zte/hayes/original_rom/system/lib/libqsap_sdk.so:system/lib/libqsap_sdk.so \
    device/zte/hayes/original_rom/system/lib/libQSEEComAPI.so:system/lib/libQSEEComAPI.so \
    device/zte/hayes/original_rom/system/lib/libquipc_os_api.so:system/lib/libquipc_os_api.so \
    device/zte/hayes/original_rom/system/lib/libquipc_ulp_adapter.so:system/lib/libquipc_ulp_adapter.so \
    device/zte/hayes/original_rom/system/lib/libQWiFiSoftApCfg.so:system/lib/libQWiFiSoftApCfg.so \
    device/zte/hayes/original_rom/system/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
    device/zte/hayes/original_rom/system/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    device/zte/hayes/original_rom/system/lib/librpc.so:system/lib/librpc.so \
    device/zte/hayes/original_rom/system/lib/libsc-a2xx.so:system/lib/libsc-a2xx.so \
    device/zte/hayes/original_rom/system/lib/libsc-a3xx.so:system/lib/libsc-a3xx.so \
    device/zte/hayes/original_rom/system/lib/libsensor1.so:system/lib/libsensor1.so \
    device/zte/hayes/original_rom/system/lib/libSHIMDivxDrm.so:system/lib/libSHIMDivxDrm.so \
    device/zte/hayes/original_rom/system/lib/libsmartinput_oem.so:system/lib/libsmartinput_oem.so \
    device/zte/hayes/original_rom/system/lib/libSMCoreCommon.so:system/lib/libSMCoreCommon.so \
    device/zte/hayes/original_rom/system/lib/libSMEvent.so:system/lib/libSMEvent.so \
    device/zte/hayes/original_rom/system/lib/libspeexwrapper.so:system/lib/libspeexwrapper.so \
    device/zte/hayes/original_rom/system/lib/libsrsprocessing.so:system/lib/libsrsprocessing.so \
    device/zte/hayes/original_rom/system/lib/libsurfaceflinger_client.so:system/lib/libsurfaceflinger_client.so \
    device/zte/hayes/original_rom/system/lib/libSwypeCore.so:system/lib/libSwypeCore.so \
    device/zte/hayes/original_rom/system/lib/libTamperDetect.so:system/lib/libTamperDetect.so \
    device/zte/hayes/original_rom/system/lib/libtcpfinaggr.so:system/lib/libtcpfinaggr.so \
    device/zte/hayes/original_rom/system/lib/libtilerenderer.so:system/lib/libtilerenderer.so \
    device/zte/hayes/original_rom/system/lib/libtime_genoff.so:system/lib/libtime_genoff.so \
    device/zte/hayes/original_rom/system/lib/libtinyxml.so:system/lib/libtinyxml.so \
    device/zte/hayes/original_rom/system/lib/libtitan.so:system/lib/libtitan.so \
    device/zte/hayes/original_rom/system/lib/libtzplayready.so:system/lib/libtzplayready.so \
    device/zte/hayes/original_rom/system/lib/libulp2.so:system/lib/libulp2.so \
    device/zte/hayes/original_rom/system/lib/libulp.so:system/lib/libulp.so \
    device/zte/hayes/original_rom/system/lib/libv8.so:system/lib/libv8.so \
    device/zte/hayes/original_rom/system/lib/libvdmengine.so:system/lib/libvdmengine.so \
    device/zte/hayes/original_rom/system/lib/libvdmfumo.so:system/lib/libvdmfumo.so \
    device/zte/hayes/original_rom/system/lib/libvideochat_jni.so:system/lib/libvideochat_jni.so \
    device/zte/hayes/original_rom/system/lib/libvideochat_stabilize.so:system/lib/libvideochat_stabilize.so \
    device/zte/hayes/original_rom/system/lib/libvoicesearch.so:system/lib/libvoicesearch.so \
    device/zte/hayes/original_rom/system/lib/libwebkitaccel.so:system/lib/libwebkitaccel.so \
    device/zte/hayes/original_rom/system/lib/libwfdcommonutils.so:system/lib/libwfdcommonutils.so \
    device/zte/hayes/original_rom/system/lib/libwfdhdcpcp.so:system/lib/libwfdhdcpcp.so \
    device/zte/hayes/original_rom/system/lib/libwfdmmsrc.so:system/lib/libwfdmmsrc.so \
    device/zte/hayes/original_rom/system/lib/libwfdmmutils.so:system/lib/libwfdmmutils.so \
    device/zte/hayes/original_rom/system/lib/libwfdnative.so:system/lib/libwfdnative.so \
    device/zte/hayes/original_rom/system/lib/libwfdrtsp.so:system/lib/libwfdrtsp.so \
    device/zte/hayes/original_rom/system/lib/libwfdsm.so:system/lib/libwfdsm.so \
    device/zte/hayes/original_rom/system/lib/libwfduibcinterface.so:system/lib/libwfduibcinterface.so \
    device/zte/hayes/original_rom/system/lib/libwfduibcsrcinterface.so:system/lib/libwfduibcsrcinterface.so \
    device/zte/hayes/original_rom/system/lib/libwfduibcsrc.so:system/lib/libwfduibcsrc.so \
    device/zte/hayes/original_rom/system/lib/libwifi_ftm_jni.so:system/lib/libwifi_ftm_jni.so \
    device/zte/hayes/original_rom/system/lib/libwifi_ftm.so:system/lib/libwifi_ftm.so \
    device/zte/hayes/original_rom/system/lib/libwifiscanner.so:system/lib/libwifiscanner.so \
    device/zte/hayes/original_rom/system/lib/libwiperjni_v02.so:system/lib/libwiperjni_v02.so \
    device/zte/hayes/original_rom/system/lib/libwnndict_oem.so:system/lib/libwnndict_oem.so \
    device/zte/hayes/original_rom/system/lib/libWVphoneAPI.so:system/lib/libWVphoneAPI.so \
    device/zte/hayes/original_rom/system/lib/libxml2.so:system/lib/libxml2.so \
    device/zte/hayes/original_rom/system/lib/libxml.so:system/lib/libxml.so \
    device/zte/hayes/original_rom/system/lib/libxt_v02.so:system/lib/libxt_v02.so \
    device/zte/hayes/original_rom/system/lib/libztedrmcore.so:system/lib/libztedrmcore.so \
    device/zte/hayes/original_rom/system/lib/libztedrmjni.so:system/lib/libztedrmjni.so \
    device/zte/hayes/original_rom/system/lib/pp_proc_plugin.so:system/lib/pp_proc_plugin.so \
    device/zte/hayes/original_rom/system/lib/qnet-plugin.so:system/lib/qnet-plugin.so \
    device/zte/hayes/original_rom/system/lib/tcp-connections.so:system/lib/tcp-connections.so \
    device/zte/hayes/original_rom/system/lib/egl/egl.cfg:system/lib/egl/egl.cfg \
    device/zte/hayes/original_rom/system/lib/egl/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
    device/zte/hayes/original_rom/system/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    device/zte/hayes/original_rom/system/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    device/zte/hayes/original_rom/system/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    device/zte/hayes/original_rom/system/lib/egl/libGLESv2S3D_adreno200.so:system/lib/egl/libGLESv2S3D_adreno200.so \
    device/zte/hayes/original_rom/system/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
    device/zte/hayes/original_rom/system/lib/hw/alsa.msm8960.so:system/lib/hw/alsa.msm8960.so \
    device/zte/hayes/original_rom/system/lib/hw/audio.a2dp.default.so:system/lib/hw/audio.a2dp.default.so \
    device/zte/hayes/original_rom/system/lib/hw/audio_policy.msm8960.so:system/lib/hw/audio_policy.msm8960.so \
    device/zte/hayes/original_rom/system/lib/hw/audio.primary.msm8960.so:system/lib/hw/audio.primary.msm8960.so \
    device/zte/hayes/original_rom/system/lib/hw/camera.msm8960.so:system/lib/hw/camera.msm8960.so \
    device/zte/hayes/original_rom/system/lib/hw/copybit.msm8960.so:system/lib/hw/copybit.msm8960.so \
    device/zte/hayes/original_rom/system/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    device/zte/hayes/original_rom/system/lib/hw/nfc.pn544.so:system/lib/hw/nfc.pn544.so \
    device/zte/hayes/original_rom/system/lib/hw/sensors.msm8960.so:system/lib/hw/sensors.msm8960.so
    
# Kernel modules
PRODUCT_COPY_FILES += \
    device/zte/hayes/original_rom/system/lib/modules/ansi_cprng.ko:system/lib/modules/ansi_cprng.ko \
    device/zte/hayes/original_rom/system/lib/modules/bluetooth-power.ko:system/lib/modules/bluetooth-power.ko \
    device/zte/hayes/original_rom/system/lib/modules/dma_test.ko:system/lib/modules/dma_test.ko \
    device/zte/hayes/original_rom/system/lib/modules/eeprom_93cx6.ko:system/lib/modules/eeprom_93cx6.ko \
    device/zte/hayes/original_rom/system/lib/modules/evbug.ko:system/lib/modules/evobug.ko \
    device/zte/hayes/original_rom/system/lib/modules/gspca_main.ko:system/lib/modules/gspca_main.ko \
    device/zte/hayes/original_rom/system/lib/modules/ks8851.ko:system/lib/modules/ks8851.ko \
    device/zte/hayes/original_rom/system/lib/modules/lcd.ko:system/lib/modules/lcd.ko \
    device/zte/hayes/original_rom/system/lib/modules/mmc_test.ko:system/lib/modules/mmc_test.ko \
    device/zte/hayes/original_rom/system/lib/modules/msm-buspm-dev.ko:system/lib/modules/msm-buspm-dev.ko \
    device/zte/hayes/original_rom/system/lib/modules/qce40.ko:system/lib/modules/qce40.ko \
    device/zte/hayes/original_rom/system/lib/modules/qcedev.ko:system/lib/modules/qcedev.ko \
    device/zte/hayes/original_rom/system/lib/modules/qcrypto.ko:system/lib/modules/qcrypto.ko \
    device/zte/hayes/original_rom/system/lib/modules/radio-iris-transport.ko:system/lib/modules/radio-iris-transport.ko \
    device/zte/hayes/original_rom/system/lib/modules/reset_modem.ko:system/lib/modules/reset_modem.ko \
    device/zte/hayes/original_rom/system/lib/modules/scsi_wait_scan.ko:system/lib/modules/scsi_wait_scan.ko \
    device/zte/hayes/original_rom/system/lib/modules/spidev.ko:system/lib/modules/spidev.ko \
    device/zte/hayes/original_rom/system/lib/modules/zte_krait_oc.ko:system/lib/modules/zte_krait_oc.ko \
    device/zte/hayes/original_rom/system/lib/modules/prima/prima_wlan.ko:system/lib/modules/prima/prima_wlan.ko

# Prebuilts bin
PRODUCT_COPY_FILES += \
    device/zte/hayes/original_rom/system/bin/akmd8962_new:system/bin/akmd8962_new \
    device/zte/hayes/original_rom/system/bin/acdbtest:system/bin/acdbtest \
    device/zte/hayes/original_rom/system/bin/ATFWD-daemon:system/bin/ATFWD-daemon \
    device/zte/hayes/original_rom/system/bin/badblocks:system/bin/badblocks \
    device/zte/hayes/original_rom/system/bin/battery_charging:system/bin/battery_charging \
    device/zte/hayes/original_rom/system/bin/bluetoothd:system/bin/bluetoothd \
    device/zte/hayes/original_rom/system/bin/brcm_patchram_plus:system/bin/brcm_patchram_plus \
    device/zte/hayes/original_rom/system/bin/bridgemgrd:system/bin/bridgemgrd \
    device/zte/hayes/original_rom/system/bin/btnvtool:system/bin/btnvtool \
    device/zte/hayes/original_rom/system/bin/bt_ssp_debug_mode.sh:system/bin/bt_ssp_debug_mode.sh \
    device/zte/hayes/original_rom/system/bin/bt_testmode_new.sh:system/bin/bt_testmode_new.sh \
    device/zte/hayes/original_rom/system/bin/bt_testmode.sh:system/bin/bt_testmode.sh \
    device/zte/hayes/original_rom/system/bin/busybox:system/bin/busybox \
    device/zte/hayes/original_rom/system/bin/ccid_daemon:system/bin/ccid_daemon \
    device/zte/hayes/original_rom/system/bin/checkdata:system/bin/checkdata \
    device/zte/hayes/original_rom/system/bin/cnd:system/bin/cnd \
    device/zte/hayes/original_rom/system/bin/config_serialno:system/bin/config_serialno \
    device/zte/hayes/original_rom/system/bin/copypartnerapp:system/bin/copypartnerapp \
    device/zte/hayes/original_rom/system/bin/curl:system/bin/curl \
    device/zte/hayes/original_rom/system/bin/diag_klog:system/bin/diag_klog \
    device/zte/hayes/original_rom/system/bin/diag_mdlog:system/bin/diag_mdlog \
    device/zte/hayes/original_rom/system/bin/diag_uart_log:system/bin/diag_uart_log \
    device/zte/hayes/original_rom/system/bin/drmdiagapp:system/bin/drmdiagapp \
    device/zte/hayes/original_rom/system/bin/ds_fmc_appd:system/bin/ds_fmc_appd \
    device/zte/hayes/original_rom/system/bin/dspcrashd:system/bin/dspcrashd \
    device/zte/hayes/original_rom/system/bin/dun-server:system/bin/dun-server \
    device/zte/hayes/original_rom/system/bin/ext4check.sh:system/bin/ext4check.sh \
    device/zte/hayes/original_rom/system/bin/fixebr:system/bin/fixebr \
    device/zte/hayes/original_rom/system/bin/fixebr.sh:system/bin/fixebr.sh \
    device/zte/hayes/original_rom/system/bin/fmconfig:system/bin/fmconfig \
    device/zte/hayes/original_rom/system/bin/fm_qsoc_patches:system/bin/fm_qsoc_patches \
    device/zte/hayes/original_rom/system/bin/format_vfat:system/bin/format_vfat \
    device/zte/hayes/original_rom/system/bin/ftmdaemon:system/bin/ftmdaemon \
    device/zte/hayes/original_rom/system/bin/ftmdaemon-oem:system/bin/ftmdaemon-oem \
    device/zte/hayes/original_rom/system/bin/gatttool:system/bin/gatttool \
    device/zte/hayes/original_rom/system/bin/getlogtofile:system/bin/getlogtofile \
    device/zte/hayes/original_rom/system/bin/GetWiFiID:system/bin/GetWiFiID \
    device/zte/hayes/original_rom/system/bin/gsensor_test:system/bin/gsensor_test \
    device/zte/hayes/original_rom/system/bin/gsiff_daemon:system/bin/gsiff_daemon \
    device/zte/hayes/original_rom/system/bin/hciattach:system/bin/hciattach \
    device/zte/hayes/original_rom/system/bin/hciconfig:system/bin/hciconfig \
    device/zte/hayes/original_rom/system/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    device/zte/hayes/original_rom/system/bin/hcitool:system/bin/hcitool \
    device/zte/hayes/original_rom/system/bin/hdmid:system/bin/hdmid \
    device/zte/hayes/original_rom/system/bin/hibernate:system/bin/hibernate \
    device/zte/hayes/original_rom/system/bin/hm_format_carrier.sh:system/bin/hm_format_carrier.sh \
    device/zte/hayes/original_rom/system/bin/hostapd:system/bin/hostapd \
    device/zte/hayes/original_rom/system/bin/hostapd_cli:system/bin/hostapd_cli \
    device/zte/hayes/original_rom/system/bin/init.btprop.sh:system/bin/init.btprop.sh \
    device/zte/hayes/original_rom/system/bin/isdbtmmtest:system/bin/isdbtmmtest \
    device/zte/hayes/original_rom/system/bin/iw:system/bin/iw \
    device/zte/hayes/original_rom/system/bin/iwconfig:system/bin/iwconfig \
    device/zte/hayes/original_rom/system/bin/iwevent:system/bin/iwevent \
    device/zte/hayes/original_rom/system/bin/iwgetid:system/bin/iwgetid \
    device/zte/hayes/original_rom/system/bin/iwlist:system/bin/iwlist \
    device/zte/hayes/original_rom/system/bin/iwmulticall:system/bin/iwmulticall \
    device/zte/hayes/original_rom/system/bin/iwpriv:system/bin/iwpriv \
    device/zte/hayes/original_rom/system/bin/iwspy:system/bin/iwspy \
    device/zte/hayes/original_rom/system/bin/mke2fs:system/bin/mke2fs \
    device/zte/hayes/original_rom/system/bin/mm-adec-omxaac-test:system/bin/mm-adec-omxaac-test \
    device/zte/hayes/original_rom/system/bin/mm-adec-omxwma-test:system/bin/mm-adec-omxwma-test \
    device/zte/hayes/original_rom/system/bin/mm-aenc-omxaac-test:system/bin/mm-aenc-omxaac-test \
    device/zte/hayes/original_rom/system/bin/mm-aenc-omxamr-test:system/bin/mm-aenc-omxamr-test \
    device/zte/hayes/original_rom/system/bin/mm-aenc-omxevrc-test:system/bin/mm-aenc-omxevrc-test \
    device/zte/hayes/original_rom/system/bin/mm-aenc-omxqcelp13-test:system/bin/mm-aenc-omxqcelp13-test \
    device/zte/hayes/original_rom/system/bin/mm-audio-alsa-test:system/bin/mm-audio-alsa-test \
    device/zte/hayes/original_rom/system/bin/mm-jpeg-dec-test:system/bin/mm-jpeg-dec-test \
    device/zte/hayes/original_rom/system/bin/mm-jpeg-dec-test-client:system/bin/mm-jpeg-dec-test-client \
    device/zte/hayes/original_rom/system/bin/mm-jpeg-enc-test:system/bin/mm-jpeg-enc-test \
    device/zte/hayes/original_rom/system/bin/mm-jpeg-enc-test-client:system/bin/mm-jpeg-enc-test-client \
    device/zte/hayes/original_rom/system/bin/mm-jps-enc-test:system/bin/mm-jps-enc-test \
    device/zte/hayes/original_rom/system/bin/mm-mpo-dec-test:system/bin/mm-mpo-dec-test \
    device/zte/hayes/original_rom/system/bin/mm-mpo-enc-test:system/bin/mm-mpo-enc-test \
    device/zte/hayes/original_rom/system/bin/mm-pp-daemon:system/bin/mm-pp-daemon \
    device/zte/hayes/original_rom/system/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    device/zte/hayes/original_rom/system/bin/mm-qcamera-test:system/bin/mm-qcamera-test \
    device/zte/hayes/original_rom/system/bin/mm-qcamera-testsuite-client:system/bin/mm-qcamera-testsuite-client \
    device/zte/hayes/original_rom/system/bin/mpdecision:system/bin/mpdecision \
    device/zte/hayes/original_rom/system/bin/msensor_test:system/bin/msensor_test \
    device/zte/hayes/original_rom/system/bin/netmgrd:system/bin/netmgrd \
    device/zte/hayes/original_rom/system/bin/nl_listener:system/bin/nl_listener \
    device/zte/hayes/original_rom/system/bin/omx_tests:system/bin/omx_tests \
    device/zte/hayes/original_rom/system/bin/pand:system/bin/pand \
    device/zte/hayes/original_rom/system/bin/port-bridge:system/bin/port-bridge \
    device/zte/hayes/original_rom/system/bin/powertop:system/bin/powertop \
    device/zte/hayes/original_rom/system/bin/profiler_daemon:system/bin/profiler_daemon \
    device/zte/hayes/original_rom/system/bin/proximity.init:system/bin/proximity.init \
    device/zte/hayes/original_rom/system/bin/ptt_socket_app:system/bin/ptt_socket_app \
    device/zte/hayes/original_rom/system/bin/qcci_adc_test:system/bin/qcci_adc_test \
    device/zte/hayes/original_rom/system/bin/qmiproxy:system/bin/qmiproxy \
    device/zte/hayes/original_rom/system/bin/qmuxd:system/bin/qmuxd \
    device/zte/hayes/original_rom/system/bin/qseecomd:system/bin/qseecomd \
    device/zte/hayes/original_rom/system/bin/qseecom_sample_client:system/bin/qseecom_sample_client \
    device/zte/hayes/original_rom/system/bin/qseecom_security_test:system/bin/qseecom_security_test \
    device/zte/hayes/original_rom/system/bin/quipc_igsn:system/bin/quipc_igsn \
    device/zte/hayes/original_rom/system/bin/quipc_main:system/bin/quipc_main \
    device/zte/hayes/original_rom/system/bin/radish:system/bin/radish \
    device/zte/hayes/original_rom/system/bin/resize2fs:system/bin/resize2fs \
    device/zte/hayes/original_rom/system/bin/rmt_storage:system/bin/rmt_storage \
    device/zte/hayes/original_rom/system/bin/sapd:system/bin/sapd \
    device/zte/hayes/original_rom/system/bin/sdlog:system/bin/sdlog \
    device/zte/hayes/original_rom/system/bin/sdptool:system/bin/sdptool \
    device/zte/hayes/original_rom/system/bin/sensors.qcom:system/bin/sensors.qcom \
    device/zte/hayes/original_rom/system/bin/simg2img:system/bin/simg2img \
    device/zte/hayes/original_rom/system/bin/sprintdiag:system/bin/sprintdiag \
    device/zte/hayes/original_rom/system/bin/stop_mdlog:system/bin/stop_mdlog \
    device/zte/hayes/original_rom/system/bin/StoreKeybox:system/bin/StoreKeybox \
    device/zte/hayes/original_rom/system/bin/test_gemini:system/bin/test_gemini \
    device/zte/hayes/original_rom/system/bin/thermald:system/bin/thermald \
    device/zte/hayes/original_rom/system/bin/time_daemon:system/bin/time_daemon \
    device/zte/hayes/original_rom/system/bin/tune2fs:system/bin/tune2fs \
    device/zte/hayes/original_rom/system/bin/usbhub:system/bin/usbhub \
    device/zte/hayes/original_rom/system/bin/usbhub_init:system/bin/usbhub_init \
    device/zte/hayes/original_rom/system/bin/usbmanutag:system/bin/usbmanutag \
    device/zte/hayes/original_rom/system/bin/v4l2-qcamera-app:system/bin/v4l2-qcamera-app \
    device/zte/hayes/original_rom/system/bin/vfat_valid:system/bin/vfat_valid \
    device/zte/hayes/original_rom/system/bin/vfat_valid.sh:system/bin/vfat_valid.sh \
    device/zte/hayes/original_rom/system/bin/wifi_ftmd:system/bin/wifi_ftmd \
    device/zte/hayes/original_rom/system/bin/wiperiface_v02:system/bin/wiperiface_v02 \
    device/zte/hayes/original_rom/system/bin/wpa_cli:system/bin/wpa_cli \
    device/zte/hayes/original_rom/system/bin/wpa_supplicant:system/bin/wpa_supplicant \
    device/zte/hayes/original_rom/system/bin/zte_charger:system/bin/zte_charger

# Prebuilts usr
PRODUCT_COPY_FILES += \
    device/zte/hayes/original_rom/system/usr/keychars/qwerty.kcm:system/usr/keychars/qwerty.kcm \
    device/zte/hayes/original_rom/system/usr/keychars/qwerty2.kcm:system/usr/keychars/qwerty2.kcm \
    device/zte/hayes/original_rom/system/usr/keylayout/atmel-touchscreen.kl:system/usr/keylayout/atmel-touchscreen.kl \
    device/zte/hayes/original_rom/system/usr/keylayout/AVRCP.kl:system/usr/keylayout/AVRCP.kl \
    device/zte/hayes/original_rom/system/usr/keylayout/Fts-touchscreen.kl:system/usr/keylayout/Fts-touchscreen.kl \
    device/zte/hayes/original_rom/system/usr/keylayout/keypad_8960.kl:system/usr/keylayout/keypad_8960.kl \
    device/zte/hayes/original_rom/system/usr/keylayout/msm8960-snd-card_Button_Jack.kl:system/usr/keylayout/msm8960-snd-card_Button_Jack.kl \
    device/zte/hayes/original_rom/system/usr/keylayout/qwerty.kl:system/usr/keylayout/qwerty.kl \
    device/zte/hayes/original_rom/system/usr/keylayout/syna-touchscreen.kl:system/usr/keylayout/syna-touchscreen.kl \
    device/zte/hayes/original_rom/system/usr/idc/qwerty.idc:system/usr/keylayout/qwerty.idc \
    device/zte/hayes/original_rom/system/usr/idc/qwerty2.idc:system/usr/keylayout/qwerty2.idc \
    device/zte/hayes/original_rom/system/usr/idc/Fts-touchscreen.idc:system/usr/keylayout/Fts-touchscreen.idc \
    device/zte/hayes/original_rom/system/usr/idc/syna-touchscreen.idc:system/usr/keylayout/syna-touchscreen.idc 
    
# Prebuilts firmware
PRODUCT_COPY_FILES += \
    device/zte/hayes/original_rom/system/etc/firmware/wlan/prima/WCNSS_cfg.dat:system/etc/firmware/wlan/prima/WCNSS_cfg.dat \
    device/zte/hayes/original_rom/system/etc/firmware/wlan/prima/WCNSS_qcom_cfg.ini:system/etc/firmware/wlan/prima/WCNSS_qcom_cfg.ini \
    device/zte/hayes/original_rom/system/etc/firmware/wlan/prima/WCNSS_qcom_wlan_nv.bin:system/etc/firmware/wlan/prima/WCNSS_qcom_wlan_nv.bin \
    device/zte/hayes/original_rom/system/etc/firmware/a225_pfp.fw:system/etc/firmware/a225_pfp.fw \
    device/zte/hayes/original_rom/system/etc/firmware/a225_pm4.fw:system/etc/firmware/a225_pm4.fw \
    device/zte/hayes/original_rom/system/etc/firmware/a225p5_pm4.fw:system/etc/firmware/a225p5_pm4.fw \
    device/zte/hayes/original_rom/system/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
    device/zte/hayes/original_rom/system/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
    device/zte/hayes/original_rom/system/etc/firmware/cyttsp_8960_cdp.hex:system/etc/firmware/cyttsp_8960_cdp.hex \
    device/zte/hayes/original_rom/system/etc/firmware/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw \
    device/zte/hayes/original_rom/system/etc/firmware/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw \
    device/zte/hayes/original_rom/system/etc/firmware/vidc.b00:system/etc/firmware/vidc.b00 \
    device/zte/hayes/original_rom/system/etc/firmware/vidc.b01:system/etc/firmware/vidc.b01 \
    device/zte/hayes/original_rom/system/etc/firmware/vidc.b02:system/etc/firmware/vidc.b02 \
    device/zte/hayes/original_rom/system/etc/firmware/vidc.b03:system/etc/firmware/vidc.b03 \
    device/zte/hayes/original_rom/system/etc/firmware/vidc.mdt:system/etc/firmware/vidc.mdt \
    device/zte/hayes/original_rom/system/etc/firmware/vidc_1080p.fw:system/etc/firmware/vidc_1080p.fw \
    device/zte/hayes/original_rom/system/etc/firmware/vidcfw.elf:system/etc/firmware/vidcfw.elf 

# Prebuilts framework
PRODUCT_COPY_FILES += \
    device/zte/hayes/original_rom/system/framework/cneapiclient.jar:system/framework/cneapiclient.jar \
    device/zte/hayes/original_rom/system/framework/com.qualcomm.location.vzw_library.jar:system/framework/com.qualcomm.location.vzw_library.jar \
    device/zte/hayes/original_rom/system/framework/com.quicinc.cne.jar:system/framework/com.quicinc.cne.jar \
    device/zte/hayes/original_rom/system/framework/modemwarmup.jar:system/framework/modemwarmup.jar \
    device/zte/hayes/original_rom/system/framework/qcnvitems.jar:system/framework/qcnvitems.jar \
    device/zte/hayes/original_rom/system/framework/qcrilhook.jar:system/framework/qcrilhook.jar 

# Prebuilts apn
PRODUCT_COPY_FILES += \
    device/zte/hayes/original_rom/system/etc/apns-conf.xml:system/etc/apns-conf.xml   